export const CONSTANTS = {
  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DEFAULT_TASK_PAGE_SIZE: 50,
  MAX_TASK_PAGE_SIZE: 100,

  // WIP Limits
  DEFAULT_WIP_LIMIT: 5,
  DEFAULT_IN_PROGRESS_WIP_LIMIT: 3,
  DEFAULT_REVIEW_WIP_LIMIT: 2,

  // Timeouts (in milliseconds)
  SOCKET_RECONNECT_DELAY: 1000,
  SOCKET_RECONNECT_DELAY_MAX: 30000,
  SOCKET_MAX_RECONNECT_ATTEMPTS: 10,
  SOCKET_CONNECTION_TIMEOUT: 10000,

  // Token expiry
  SESSION_COOKIE_EXPIRY_DAYS: 7,

  // Rate limits
  LOGIN_ATTEMPTS: 5,
  LOGIN_WINDOW_MS: 5 * 60 * 1000, // 5 minutes
  REGISTER_ATTEMPTS: 3,
  REGISTER_WINDOW_MS: 60 * 60 * 1000, // 1 hour
  ADMIN_CREATE_ATTEMPTS: 10,
  ADMIN_CREATE_WINDOW_MS: 60 * 60 * 1000, // 1 hour

  // Validation
  MAX_TITLE_LENGTH: 200,
  MAX_DESCRIPTION_LENGTH: 5000,
  MAX_LABELS: 10,
  MAX_LABEL_LENGTH: 50,
  MIN_PASSWORD_LENGTH: 8,

  // File uploads
  MAX_ATTACHMENT_SIZE_MB: 50,
  MAX_ATTACHMENT_SIZE_BYTES: 50 * 1024 * 1024,

  // Undo history
  MAX_UNDO_HISTORY: 20,

  // Cursor
  CURSOR_THROTTLE_MS: 50,

  // Toast durations
  TOAST_SUCCESS_DURATION: 3000,
  TOAST_ERROR_DURATION: 5000,
  TOAST_LONG_ERROR_DURATION: 10000,

  // Dates
  DATE_TIMEZONE: 'UTC',
} as const

export type Constants = typeof CONSTANTS